"""Paddock news ticker headline templates."""

TEMPLATES = {
    "trade": [
        "Sources say {team} signed {player} for 'driver synergy' and a bag of test slots",
        "BREAKING: {team} prises {player} away from {partner} — insiders cite 'vibes'",
        "{team} and {partner} complete a deal for {player}. Nobody in the paddock clapped.",
        "Transfer alert: {player} is headed to {team}. Sim-racers in shambles.",
        "{team} lands {player} in a swap described as 'mutually confusing'",
        "Paddock sources: {player} to {team}. Previous team sends a thumbs-up emoji.",
        "{team} adds {player}; the data engineers are still loading the spreadsheet",
        "BLOCKBUSTER: {player} joins {team}. Hospitality unit erupts.",
        "{team} got {player} for 'future considerations' — the future looks nervous",
        "Transfer wire: {player} joins {team}. Old crew unfollowed on Instagram.",
    ],
    "signing": [
        "{player} signs with {team} for €{salary}M/yr, reportedly for the motorhome espresso",
        "{team} lands {player} on a €{salary}M deal — manager calls it 'market rate, emotionally'",
        "Silly season: {player} chooses {team} over literally sleeping on it",
        "{player} inks with {team}. Retainer: €{salary}M. Happiness: pending.",
        "{team} signs {player} (€{salary}M). The accountants are sweating in the garage.",
        "{player} picks {team} after an exhaustive 48-hour deliberation",
        "Deal done: {player} to {team} for €{salary}M. Paddock TV cameras incoming.",
        "{team} wins the {player} race with good catering and a quick pit crew",
        "{player} agrees €{salary}M with {team}; cites 'great weather and a fast pit lane'",
        "Driver market splash: {team} adds {player} on €{salary}M/yr",
    ],
    "rejection": [
        "{player} declined {team}'s €{salary}M offer, calling it 'a paddock pass salary'",
        "{player} told {team} to come back — with more zeros",
        "Sources: {player} rejected {team}'s offer and went karting instead",
        "{player} passed on {team}. 'I know my lap times,' said someone who definitely does.",
        "{team}'s €{salary}M pitch to {player} met with a polite 'nah'",
        "{player} ghosted {team}'s top offer. Respectfully.",
        "Report: {player} laughed, then declined {team}'s €{salary}M",
        "{team} whiffed on {player}. Budget intact, dignity questionable.",
    ],
    "injury": [
        "{player} ruled OUT for the next round ({detail})",
        "{player} is day-to-day with a classic case of being too quick",
        "Medical report: {player} — {detail}. Rival crews nod solemnly.",
        "{team}: {player} sidelined. Reason: {detail}",
        "{player} stood down with {detail}. Reserve driver on standby.",
        "Update: {player} ({detail}). Return timeline: TBD, vibes willing.",
        "{team} rules out {player} ({detail}). Backup plan: the development driver.",
    ],
    "race_win": [
        "{team} wins the {race} in {cls}; rivals file a complaint with the stewards",
        "VICTORY: {team} takes {cls} honours at the {race}",
        "{team} converts pole into a {cls} win at the {race}. Champagne shower budget exceeded.",
        "Lights to flag: {team} dominates {cls} at the {race}",
        "{team} grabs the {cls} win at the {race}. The garage is dancing.",
        "{race} result: {team} on top in {cls}. Engineers high-five air.",
    ],
    "upset": [
        "UPSET: {team} wins the {race} from P{grid} on the grid. Strategy chalkboards weep.",
        "{team} charges from P{grid} to win the {race}. Vegas shrugs.",
        "Nobody saw this: {team} takes the {race} starting P{grid}",
        "Shock result: {team} wins the {race} after lining up P{grid}",
        "Stunner at the {race}: {team} climbs from P{grid} to victory",
    ],
    "rookie": [
        "Rookie watch: {player} ({team}) already looks like a steal at {overall} OVR",
        "Paddock buzzing about {player} — {team}'s rookie is turning heads",
        "Scouts rave about {player}; {team} may have found a future works driver",
        "Rookie sensation: {player} putting {team} on notice with elite pace",
        "{player} is {team}'s rookie gem — sim-racing Twitter in meltdown mode",
        "Hot rookie alert: {player} ({team}) driving like a veteran already",
        "Breakout rookie {player} has {team} fans refreshing the timing screens",
        "Rookie radar: {player} at {overall} OVR and climbing for {team}",
    ],
    "draft": [
        "{team} signs {player} to the academy; scout notes: 'he looks fast on the sim'",
        "Young Driver Programme: {team} picks up {player}. Paddock Twitter is undefeated.",
        "{team} adds {player} to its junior squad. Ceiling: stratosphere, allegedly.",
        "Academy intake: {team} grabs {player}. Analysts say 'sure, why not'",
        "{team} tabs {player} for the development pool. Mock rankings in shambles.",
        "{team} signs {player}; mum cries, dad nods approvingly in the grandstand",
        "Young driver news: {player} to {team}'s academy. Future TBD.",
    ],
    "fa_departure": [
        "{player} ({age}) steps away from endurance racing after going unsigned",
        "No seats left: {player} heads to GT racing at {age}",
        "{player} calls time on a WEC return at {age}",
        "Driver market exit: {player} ({age}) is done waiting for a drive",
    ],
    "retirement": [
        "{player} hangs up the helmet at {age}; paddock mourns, rival GMs rejoice",
        "{player} announces retirement. Onboard reel loading…",
        "End of an era: {player} retires. Someone please tell their manager.",
        "{player} calls it a career at {age}. Helmet retirement pending a vibes check.",
        "Retirement: {player} ({age}). The grid will miss the stories.",
        "{player} steps out of the cockpit at {age}. Sponsor deal survives.",
    ],
    "pick_trade": [
        "{team} traded a slot for a {year} R{round} young-driver pick. Time travel confirmed.",
        "Academy trade: {team} swaps slots for {year} R{round}. GM playing 4D chess (probably).",
        "{team} moves for a {year} R{round} test slot. Fans debate for 72 hours.",
        "Slot swap: {team} acquires {year} R{round}. Future self thanks them.",
        "{team} trades development capital for {year} R{round}. Spreadsheet fans rejoice.",
    ],
    "gm_personality": [
        "Paddock buzz: a team hires a {archetype} team principal — expect wild transfers",
        "Pit-wall shake-up: a new {archetype} principal takes the reins somewhere on the grid",
        "Sources say a {archetype} principal is calling the shots for a team this season",
    ],
    "championship_bonus": [
        "{team} drivers cash title bonus cheques totalling €{total}M",
        "Title night payday: {team} crew splits €{total}M in championship bonuses",
        "{team} title bonus pool: €{total}M distributed to the squad",
    ],
    "year_end": [
        "Season Review: {mvp} named Driver of the Year — full awards edition published",
        "Paddock Post drops season awards: {mvp} takes Driver of the Year for {team}",
        "Season wrap: {mvp} headlines the year-end awards report",
    ],
    "championship": [
        "CHAMPIONS: {team} win the {cls} title — the trophy is secured",
        "{team} capture the {cls} crown. Parade planning already underway.",
        "{team} are {cls} champions. Confetti budget: unlimited.",
        "Title decided: {team} clinch the {cls} championship at the finale",
        "{team} crowned {cls} champions. Champagne liability waiver signed.",
    ],
    "offcourt": [
        "{player} spotted buying 400 espressos at the circuit café 'for the engineers'",
        "{player} late to the drivers' briefing — was perfecting a sim-racing setup",
        "{player} ({team}) challenged a marshal to a footrace down the pit lane. Lost.",
        "{team} lists {player} as questionable — 'ate the entire hospitality buffet'",
        "{player} bought every energy drink in a 50-mile radius 'for the garage'",
        "{player} showed up to media day in a full retro race suit. Team said 'sure'",
        "Sources: {player} tried to overtake the safety car. On the formation lap. In the paddock.",
        "{player} ({team}) spent the off day at a go-kart track 'for science'",
        "{player} missed the team photo — was busy renaming the motorhome WiFi",
        "{team}: {player} day-to-day after losing a tyre-changing bet to a mechanic",
        "{player} cited for honking at the stewards in traffic. 'They know what they did.'",
        "Report: {player} spent €12,000 on helmet liveries, filed it as 'aero'",
        "{player} tried to draft a flock of geese on the way to the circuit",
        "{team} confirms {player} questionable — dyed hair team-livery colours on a dare",
        "{player} went viral teaching a cat to do a pit stop. Still a 2.4s stop.",
    ],
    "ambient": [
        "Series memo reminds drivers that the tyre warmers are not for making toast",
        "Sources say at least one principal still pit-boards in Comic Sans. Respect.",
        "Breaking: tyres are round, fuel saving is controversial, the sun rises in the east",
        "Anonymous driver polled: 94% would trade a test slot for uninterrupted sleep",
        "Race control denies the rumour that strategy is decided by a very large hamster wheel",
        "Tech dept confirms: most missed apexes blamed on 'kerb unfairness'",
        "Series office reminder: the safety car driver is a coworker, not a chicane",
        "Report: average driver spends 6 hours daily debating whether to post a hotlap",
        "{team} PR department wins an award for 'most creative gearbox euphemisms'",
        "Hot take: {player} would dominate if races were decided by vibes alone",
    ],
}


def template_count():
    return sum(len(items) for items in TEMPLATES.values())


def all_categories():
    return list(TEMPLATES.keys())
